use crate::models::task_command::TaskCommand;
use crate::models::debug_command::DebugCommand;

/// Represents events that occur in the user interface.
///
/// These events are generated by the UI based on user input and
/// are handled by the controller layer.
#[derive(Debug, Clone, PartialEq)]
pub enum UiEvent {
    /// Task-related command
    Task(TaskCommand),
    
    /// Debug-related command
    Debug(DebugCommand),
    
    /// User wants to see help information
    ShowHelp,
    
    /// User wants to quit the application
    Quit,
    
    /// Unknown command entered
    UnknownCommand(String),
    
    /// Invalid input (e.g., missing arguments)
    InvalidInput(String),
}
